-- MySQL Script generated by MySQL Workbench
-- Mon Apr 17 00:46:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

DROP DATABASE BANK_MANAGEMENT
GO
CREATE DATABASE BANK_MANAGEMENT
GO
USE BANK_MANAGEMENT
GO

-- -----------------------------------------------------
-- Table OWNER
-- -----------------------------------------------------
CREATE TABLE OWNER (
  idOWNER INT NOT NULL IDENTITY,
  Name NVARCHAR(150) NULL,
  Address NVARCHAR(255) NULL,
  Phone VARCHAR(15) NULL,
  Fax VARCHAR(20) NULL,
  created_by INT NULL,
  last_update_by INT NULL,
  created_date DATETIME NULL,
  last_update_date DATETIME NULL,
  PRIMARY KEY (idOWNER))
GO


-- -----------------------------------------------------
-- Table BRANCH
-- -----------------------------------------------------
CREATE TABLE BRANCH (
  idBranch INT NOT NULL IDENTITY,
  idOWNER INT NOT NULL,
  Name NVARCHAR(150) NULL,
  Address NVARCHAR(255) NULL,
  Phone VARCHAR(15) NULL,
  Fax VARCHAR(20) NULL,
  created_by INT NULL,
  last_update_by INT NULL,
  created_date DATETIME NULL,
  last_update_date DATETIME NULL,
  PRIMARY KEY (idBranch),
  INDEX fk_BRANCH_OWNER_idx (idOWNER ASC),
  CONSTRAINT fk_BRANCH_OWNER
    FOREIGN KEY (idOWNER)
    REFERENCES OWNER (idOWNER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
GO


-- -----------------------------------------------------
-- Table POSITION_EMP
-- -----------------------------------------------------
CREATE TABLE POSITION_EMP (
  idPOSITION INT NOT NULL IDENTITY,
  Name NVARCHAR(100) NULL,
  Status VARCHAR(15) NULL,
  Created_by INT NULL,
  Last_update_by INT NULL,
  Created_date DATETIME NULL,
  Last_update_date DATETIME NULL,
  PRIMARY KEY (idPOSITION))
GO


-- -----------------------------------------------------
-- Table EMPLOYEE
-- -----------------------------------------------------
CREATE TABLE EMPLOYEE (
  idEMPLOYEE INT NOT NULL IDENTITY,
  idBranch INT NOT NULL,
  idPOSITION INT NOT NULL,
  Name NVARCHAR(50) NULL,
  Address NVARCHAR(255) NULL,
  Phone VARCHAR(15) NULL,
  created_by INT NULL,
  last_update_by INT NULL,
  created_date DATETIME NULL,
  last_update_date DATETIME NULL,
  PRIMARY KEY (idEMPLOYEE),
  INDEX fk_EMPLOYEE_BRANCH1_idx (idBranch ASC),
  INDEX fk_EMPLOYEE_POSITION_EMP1_idx (idPOSITION ASC),
  CONSTRAINT fk_EMPLOYEE_BRANCH1
    FOREIGN KEY (idBranch)
    REFERENCES BRANCH (idBranch)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_EMPLOYEE_POSITION_EMP1
    FOREIGN KEY (idPOSITION)
    REFERENCES POSITION_EMP (idPOSITION)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
GO


-- -----------------------------------------------------
-- Table CUSTOMER
-- -----------------------------------------------------
CREATE TABLE CUSTOMER (
  idCUSTOMER INT NOT NULL IDENTITY,
  idBranch INT NOT NULL,
  Name NVARCHAR(55) NULL,
  Address NVARCHAR(255) NULL,
  Birthday DATE NULL,
  Sex NVARCHAR(15) NULL,
  Phone VARCHAR(15) NULL,
  Fax VARCHAR(20) NULL,
  Email VARCHAR(45) NULL,
  ID_NUMBER VARCHAR(25) NULL,
  ID_DATE DATE NULL,
  ID_PLACE NVARCHAR(155) NULL,
  Status VARCHAR(15) NULL,
  Created_by INT NULL,
  Last_update_by INT NULL,
  Created_date DATETIME NULL,
  Last_update_date DATETIME NULL,
  PRIMARY KEY (idCUSTOMER),
  INDEX fk_CUSTOMER_BRANCH1_idx (idBranch ASC),
  CONSTRAINT fk_CUSTOMER_BRANCH1
    FOREIGN KEY (idBranch)
    REFERENCES BRANCH (idBranch)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
GO


-- -----------------------------------------------------
-- Table ACCOUNT_TYPE
-- -----------------------------------------------------
CREATE TABLE ACCOUNT_TYPE (
  idACCOUNT_TYPE INT NOT NULL IDENTITY,
  Name NVARCHAR(155) NULL,
  MinBal DECIMAL NULL,
  MaxBal DECIMAL NULL,
  Status VARCHAR(15) NULL,
  Created_by INT NULL,
  Last_update_by INT NULL,
  Create_date DATETIME NULL,
  Last_update_date DATETIME NULL,
  PRIMARY KEY (idACCOUNT_TYPE))
GO


-- -----------------------------------------------------
-- Table ACCOUNT
-- -----------------------------------------------------
CREATE TABLE ACCOUNT (
  idACCOUNT INT NOT NULL IDENTITY,
  idACCOUNT_TYPE INT NOT NULL,
  idBranch INT NOT NULL,
  idCUSTOMER INT NOT NULL,
  Account_number VARCHAR(35) NOT NULL,
  Open_date DATE NULL,
  Close_date DATE NULL,
  Currentcy_code VARCHAR(15) NULL,
  Min_Balance DECIMAL NULL,
  Max_Balance DECIMAL NULL,
  Amount DECIMAL NULL,
  Status VARCHAR(15) NULL,
  Created_by INT NULL,
  Last_update_by INT NULL,
  Created_date DATETIME NULL,
  Last_update_date DATETIME NULL,
  PRIMARY KEY (idACCOUNT),
  INDEX fk_ACCOUNT_ACCOUNT_TYPE1_idx (idACCOUNT_TYPE ASC),
  INDEX fk_ACCOUNT_BRANCH1_idx (idBranch ASC),
  INDEX fk_ACCOUNT_CUSTOMER1_idx (idCUSTOMER ASC),
  CONSTRAINT fk_ACCOUNT_ACCOUNT_TYPE1
    FOREIGN KEY (idACCOUNT_TYPE)
    REFERENCES ACCOUNT_TYPE (idACCOUNT_TYPE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ACCOUNT_BRANCH1
    FOREIGN KEY (idBranch)
    REFERENCES BRANCH (idBranch)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ACCOUNT_CUSTOMER1
    FOREIGN KEY (idCUSTOMER)
    REFERENCES CUSTOMER (idCUSTOMER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
GO


-- -----------------------------------------------------
-- Table TYPE_SAVINGS_ACCOUNT
-- -----------------------------------------------------
CREATE TABLE TYPE_SAVINGS_ACCOUNT (
  idTYPE_SAVINGS_ACCOUNT INT NOT NULL IDENTITY,
  Name NVARCHAR(155) NULL,
  Status VARCHAR(15) NULL,
  Create_by INT NULL,
  Last_update_by INT NULL,
  Created_date DATETIME NULL,
  Last_update_date DATETIME NULL,
  PRIMARY KEY (idTYPE_SAVINGS_ACCOUNT))
GO


-- -----------------------------------------------------
-- Table SAVINGS_ACCOUNT
-- -----------------------------------------------------
CREATE TABLE SAVINGS_ACCOUNT (
  idSAVINGS_ACCOUNT INT NOT NULL IDENTITY,
  idTYPE_SAVINGS_ACCOUNT INT NOT NULL,
  idBranch INT NOT NULL,
  idCUSTOMER INT NOT NULL,
  idACCOUNT INT NOT NULL,
  Open_Date DATE NULL,
  Close_Date DATE NULL,
  Maturial_Date DATE NULL,
  Created_by INT NULL,
  Last_update_by INT NULL,
  Created_date DATETIME NULL,
  Last_update_date DATETIME NULL,
  Status VARCHAR(15) NULL,
  PRIMARY KEY (idSAVINGS_ACCOUNT),
  INDEX fk_SAVINGS_ACCOUNT_TYPE_SAVINGS_ACCOUNT1_idx (idTYPE_SAVINGS_ACCOUNT ASC),
  INDEX fk_SAVINGS_ACCOUNT_CUSTOMER1_idx (idCUSTOMER ASC),
  INDEX fk_SAVINGS_ACCOUNT_ACCOUNT1_idx (idACCOUNT ASC),
  INDEX fk_SAVINGS_ACCOUNT_BRANCH1_idx (idBranch ASC),
  CONSTRAINT fk_SAVINGS_ACCOUNT_TYPE_SAVINGS_ACCOUNT1
    FOREIGN KEY (idTYPE_SAVINGS_ACCOUNT)
    REFERENCES TYPE_SAVINGS_ACCOUNT (idTYPE_SAVINGS_ACCOUNT)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_SAVINGS_ACCOUNT_CUSTOMER1
    FOREIGN KEY (idCUSTOMER)
    REFERENCES CUSTOMER (idCUSTOMER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_SAVINGS_ACCOUNT_ACCOUNT1
    FOREIGN KEY (idACCOUNT)
    REFERENCES ACCOUNT (idACCOUNT)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_SAVINGS_ACCOUNT_BRANCH1
    FOREIGN KEY (idBranch)
    REFERENCES BRANCH (idBranch)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
GO


-- -----------------------------------------------------
-- Table TRANSACTION_TYPES
-- -----------------------------------------------------
CREATE TABLE TRANSACTION_TYPES (
  idTRANSACTION_TYPES INT NOT NULL IDENTITY,
  Name NVARCHAR(155) NULL,
  Status VARCHAR(15) NULL,
  Created_by INT NULL,
  Last_update_by INT NULL,
  Created_date DATETIME NULL,
  Last_update_date DATETIME NULL,
  PRIMARY KEY (idTRANSACTION_TYPES))
GO


-- -----------------------------------------------------
-- Table TRANSACTIONS
-- -----------------------------------------------------
CREATE TABLE TRANSACTIONS (
  idTRANSACTIONS INT NOT NULL IDENTITY,
  idBranch INT NOT NULL,
  idTRANSACTION_TYPES INT NOT NULL,
  idACCOUNT INT NOT NULL,
  Entered_amount DECIMAL NULL,
  Accounted_amount DECIMAL NULL,
  Fee_amount DECIMAL NULL,
  Tax_amount DECIMAL NULL,
  Currentcy_code VARCHAR(45) NULL,
  Exchange_rate DECIMAL NULL,
  Created_by INT NULL,
  Last_update_by INT NULL,
  Created_date DATETIME NULL,
  Last_update_date DATETIME NULL,
  Approver_by INT NULL,
  Approver_date DATETIME NULL,
  Status VARCHAR(15) NULL,
  PRIMARY KEY (idTRANSACTIONS),
  INDEX fk_TRANSACTIONS_TRANSACTION_TYPES1_idx (idTRANSACTION_TYPES ASC),
  INDEX fk_TRANSACTIONS_ACCOUNT1_idx (idACCOUNT ASC),
  INDEX fk_TRANSACTIONS_BRANCH1_idx (idBranch ASC),
  CONSTRAINT fk_TRANSACTIONS_TRANSACTION_TYPES1
    FOREIGN KEY (idTRANSACTION_TYPES)
    REFERENCES TRANSACTION_TYPES (idTRANSACTION_TYPES)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_TRANSACTIONS_ACCOUNT1
    FOREIGN KEY (idACCOUNT)
    REFERENCES ACCOUNT (idACCOUNT)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_TRANSACTIONS_BRANCH1
    FOREIGN KEY (idBranch)
    REFERENCES BRANCH (idBranch)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
GO


----------------------------------------

SELECT * FROM OWNER

SELECT * FROM BRANCH

SELECT * FROM POSITION_EMP

SELECT * FROM EMPLOYEE

SELECT * FROM CUSTOMER

SELECT * FROM ACCOUNT_TYPE

SELECT * FROM ACCOUNT

SELECT * FROM TYPE_SAVINGS_ACCOUNT

SELECT * FROM SAVINGS_ACCOUNT

SELECT * FROM TRANSACTION_TYPES

SELECT * FROM TRANSACTIONS