//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTTHD.WebAPI._02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public ACCOUNT()
        {
            this.SAVINGS_ACCOUNT = new HashSet<SAVINGS_ACCOUNT>();
            this.TRANSACTIONS = new HashSet<TRANSACTION>();
        }
    
        public int idACCOUNT { get; set; }
        public int idACCOUNT_TYPE { get; set; }
        public int idBranch { get; set; }
        public int idCUSTOMER { get; set; }
        public string Account_number { get; set; }
        public Nullable<System.DateTime> Open_date { get; set; }
        public Nullable<System.DateTime> Close_date { get; set; }
        public string Currentcy_code { get; set; }
        public Nullable<decimal> Min_Balance { get; set; }
        public Nullable<decimal> Max_Balance { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<int> Last_update_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> Last_update_date { get; set; }
    
        public virtual ACCOUNT_TYPE ACCOUNT_TYPE { get; set; }
        public virtual BRANCH BRANCH { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ICollection<SAVINGS_ACCOUNT> SAVINGS_ACCOUNT { get; set; }
        public virtual ICollection<TRANSACTION> TRANSACTIONS { get; set; }
    }
}
