//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTTHD.WebAPI._02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.ACCOUNTs = new HashSet<ACCOUNT>();
            this.SAVINGS_ACCOUNT = new HashSet<SAVINGS_ACCOUNT>();
        }
    
        public int idCUSTOMER { get; set; }
        public int idBranch { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Sex { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string ID_NUMBER { get; set; }
        public Nullable<System.DateTime> ID_DATE { get; set; }
        public string ID_PLACE { get; set; }
        public string Status { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<int> Last_update_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> Last_update_date { get; set; }
    
        public virtual ICollection<ACCOUNT> ACCOUNTs { get; set; }
        public virtual BRANCH BRANCH { get; set; }
        public virtual ICollection<SAVINGS_ACCOUNT> SAVINGS_ACCOUNT { get; set; }
    }
}
