//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTTHD.WebAPI._02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int idEMPLOYEE { get; set; }
        public int idBranch { get; set; }
        public int idPOSITION { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> last_update_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> last_update_date { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        public virtual POSITION_EMP POSITION_EMP { get; set; }
    }
}
