//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTTHD.WebAPI._02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAVINGS_ACCOUNT
    {
        public int idSAVINGS_ACCOUNT { get; set; }
        public int idTYPE_SAVINGS_ACCOUNT { get; set; }
        public int idBranch { get; set; }
        public int idCUSTOMER { get; set; }
        public int idACCOUNT { get; set; }
        public Nullable<System.DateTime> Open_Date { get; set; }
        public Nullable<System.DateTime> Close_Date { get; set; }
        public Nullable<System.DateTime> Maturial_Date { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<int> Last_update_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> Last_update_date { get; set; }
        public string Status { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual BRANCH BRANCH { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual TYPE_SAVINGS_ACCOUNT TYPE_SAVINGS_ACCOUNT { get; set; }
    }
}
