//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTTHD.WebAPI._02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_SAVINGS_ACCOUNT
    {
        public TYPE_SAVINGS_ACCOUNT()
        {
            this.SAVINGS_ACCOUNT = new HashSet<SAVINGS_ACCOUNT>();
        }
    
        public int idTYPE_SAVINGS_ACCOUNT { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public Nullable<int> Create_by { get; set; }
        public Nullable<int> Last_update_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> Last_update_date { get; set; }
    
        public virtual ICollection<SAVINGS_ACCOUNT> SAVINGS_ACCOUNT { get; set; }
    }
}
