package model;
// Generated May 21, 2017 1:57:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private Integer idAccount;
	private AccountType accountType;
	private Branch branch;
	private Customer customer;
	private String accountNumber;
	private Date openDate;
	private Date closeDate;
	private String currentcyCode;
	private Long minBalance;
	private Long maxBalance;
	private Long amount;
	private String status;
	private Integer createdBy;
	private Integer lastUpdateBy;
	private Date createdDate;
	private Date lastUpdateDate;
	private Set savingsAccounts = new HashSet(0);
	private Set transactionses = new HashSet(0);

	public Account() {
	}

	public Account(AccountType accountType, Branch branch, Customer customer, String accountNumber) {
		this.accountType = accountType;
		this.branch = branch;
		this.customer = customer;
		this.accountNumber = accountNumber;
	}

	public Account(AccountType accountType, Branch branch, Customer customer, String accountNumber, Date openDate,
			Date closeDate, String currentcyCode, Long minBalance, Long maxBalance, Long amount, String status,
			Integer createdBy, Integer lastUpdateBy, Date createdDate, Date lastUpdateDate, Set savingsAccounts,
			Set transactionses) {
		this.accountType = accountType;
		this.branch = branch;
		this.customer = customer;
		this.accountNumber = accountNumber;
		this.openDate = openDate;
		this.closeDate = closeDate;
		this.currentcyCode = currentcyCode;
		this.minBalance = minBalance;
		this.maxBalance = maxBalance;
		this.amount = amount;
		this.status = status;
		this.createdBy = createdBy;
		this.lastUpdateBy = lastUpdateBy;
		this.createdDate = createdDate;
		this.lastUpdateDate = lastUpdateDate;
		this.savingsAccounts = savingsAccounts;
		this.transactionses = transactionses;
	}

	public Integer getIdAccount() {
		return this.idAccount;
	}

	public void setIdAccount(Integer idAccount) {
		this.idAccount = idAccount;
	}

	public AccountType getAccountType() {
		return this.accountType;
	}

	public void setAccountType(AccountType accountType) {
		this.accountType = accountType;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public Date getOpenDate() {
		return this.openDate;
	}

	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	public String getCurrentcyCode() {
		return this.currentcyCode;
	}

	public void setCurrentcyCode(String currentcyCode) {
		this.currentcyCode = currentcyCode;
	}

	public Long getMinBalance() {
		return this.minBalance;
	}

	public void setMinBalance(Long minBalance) {
		this.minBalance = minBalance;
	}

	public Long getMaxBalance() {
		return this.maxBalance;
	}

	public void setMaxBalance(Long maxBalance) {
		this.maxBalance = maxBalance;
	}

	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Integer getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(Integer lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Set getSavingsAccounts() {
		return this.savingsAccounts;
	}

	public void setSavingsAccounts(Set savingsAccounts) {
		this.savingsAccounts = savingsAccounts;
	}

	public Set getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set transactionses) {
		this.transactionses = transactionses;
	}

}
