package model;
// Generated May 21, 2017 1:57:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer idCustomer;
	private Branch branch;
	private String name;
	private String address;
	private Date birthday;
	private String sex;
	private String phone;
	private String fax;
	private String email;
	private String idNumber;
	private Date idDate;
	private String idPlace;
	private String status;
	private Integer createdBy;
	private Integer lastUpdateBy;
	private Date createdDate;
	private Date lastUpdateDate;
	private Set accounts = new HashSet(0);
	private Set savingsAccounts = new HashSet(0);

	public Customer() {
	}

	public Customer(Branch branch) {
		this.branch = branch;
	}

	public Customer(Branch branch, String name, String address, Date birthday, String sex, String phone, String fax,
			String email, String idNumber, Date idDate, String idPlace, String status, Integer createdBy,
			Integer lastUpdateBy, Date createdDate, Date lastUpdateDate, Set accounts, Set savingsAccounts) {
		this.branch = branch;
		this.name = name;
		this.address = address;
		this.birthday = birthday;
		this.sex = sex;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.idNumber = idNumber;
		this.idDate = idDate;
		this.idPlace = idPlace;
		this.status = status;
		this.createdBy = createdBy;
		this.lastUpdateBy = lastUpdateBy;
		this.createdDate = createdDate;
		this.lastUpdateDate = lastUpdateDate;
		this.accounts = accounts;
		this.savingsAccounts = savingsAccounts;
	}

	public Integer getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(Integer idCustomer) {
		this.idCustomer = idCustomer;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public Date getIdDate() {
		return this.idDate;
	}

	public void setIdDate(Date idDate) {
		this.idDate = idDate;
	}

	public String getIdPlace() {
		return this.idPlace;
	}

	public void setIdPlace(String idPlace) {
		this.idPlace = idPlace;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Integer getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(Integer lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Set getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set accounts) {
		this.accounts = accounts;
	}

	public Set getSavingsAccounts() {
		return this.savingsAccounts;
	}

	public void setSavingsAccounts(Set savingsAccounts) {
		this.savingsAccounts = savingsAccounts;
	}

}
