package model;
// Generated May 21, 2017 1:57:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer idEmployee;
	private Branch branch;
	private PositionEmp positionEmp;
	private String name;
	private String address;
	private String phone;
	private Integer createdBy;
	private Integer lastUpdateBy;
	private Date createdDate;
	private Date lastUpdateDate;

	public Employee() {
	}

	public Employee(Branch branch, PositionEmp positionEmp) {
		this.branch = branch;
		this.positionEmp = positionEmp;
	}

	public Employee(Branch branch, PositionEmp positionEmp, String name, String address, String phone,
			Integer createdBy, Integer lastUpdateBy, Date createdDate, Date lastUpdateDate) {
		this.branch = branch;
		this.positionEmp = positionEmp;
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.createdBy = createdBy;
		this.lastUpdateBy = lastUpdateBy;
		this.createdDate = createdDate;
		this.lastUpdateDate = lastUpdateDate;
	}

	public Integer getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public PositionEmp getPositionEmp() {
		return this.positionEmp;
	}

	public void setPositionEmp(PositionEmp positionEmp) {
		this.positionEmp = positionEmp;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Integer getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(Integer lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
