package model;
// Generated May 21, 2017 1:57:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * SavingsAccount generated by hbm2java
 */
public class SavingsAccount implements java.io.Serializable {

	private Integer idSavingsAccount;
	private Account account;
	private Branch branch;
	private Customer customer;
	private TypeSavingsAccount typeSavingsAccount;
	private Date openDate;
	private Date closeDate;
	private Date maturialDate;
	private Integer createdBy;
	private Integer lastUpdateBy;
	private Date createdDate;
	private Date lastUpdateDate;
	private String status;

	public SavingsAccount() {
	}

	public SavingsAccount(Account account, Branch branch, Customer customer, TypeSavingsAccount typeSavingsAccount) {
		this.account = account;
		this.branch = branch;
		this.customer = customer;
		this.typeSavingsAccount = typeSavingsAccount;
	}

	public SavingsAccount(Account account, Branch branch, Customer customer, TypeSavingsAccount typeSavingsAccount,
			Date openDate, Date closeDate, Date maturialDate, Integer createdBy, Integer lastUpdateBy, Date createdDate,
			Date lastUpdateDate, String status) {
		this.account = account;
		this.branch = branch;
		this.customer = customer;
		this.typeSavingsAccount = typeSavingsAccount;
		this.openDate = openDate;
		this.closeDate = closeDate;
		this.maturialDate = maturialDate;
		this.createdBy = createdBy;
		this.lastUpdateBy = lastUpdateBy;
		this.createdDate = createdDate;
		this.lastUpdateDate = lastUpdateDate;
		this.status = status;
	}

	public Integer getIdSavingsAccount() {
		return this.idSavingsAccount;
	}

	public void setIdSavingsAccount(Integer idSavingsAccount) {
		this.idSavingsAccount = idSavingsAccount;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public TypeSavingsAccount getTypeSavingsAccount() {
		return this.typeSavingsAccount;
	}

	public void setTypeSavingsAccount(TypeSavingsAccount typeSavingsAccount) {
		this.typeSavingsAccount = typeSavingsAccount;
	}

	public Date getOpenDate() {
		return this.openDate;
	}

	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	public Date getMaturialDate() {
		return this.maturialDate;
	}

	public void setMaturialDate(Date maturialDate) {
		this.maturialDate = maturialDate;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Integer getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(Integer lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
