package model;
// Generated May 21, 2017 1:57:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TransactionTypes generated by hbm2java
 */
public class TransactionTypes implements java.io.Serializable {

	private Integer idTransactionTypes;
	private String name;
	private String status;
	private Integer createdBy;
	private Integer lastUpdateBy;
	private Date createdDate;
	private Date lastUpdateDate;
	private Set transactionses = new HashSet(0);

	public TransactionTypes() {
	}

	public TransactionTypes(String name, String status, Integer createdBy, Integer lastUpdateBy, Date createdDate,
			Date lastUpdateDate, Set transactionses) {
		this.name = name;
		this.status = status;
		this.createdBy = createdBy;
		this.lastUpdateBy = lastUpdateBy;
		this.createdDate = createdDate;
		this.lastUpdateDate = lastUpdateDate;
		this.transactionses = transactionses;
	}

	public Integer getIdTransactionTypes() {
		return this.idTransactionTypes;
	}

	public void setIdTransactionTypes(Integer idTransactionTypes) {
		this.idTransactionTypes = idTransactionTypes;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Integer getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(Integer lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Set getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set transactionses) {
		this.transactionses = transactionses;
	}

}
