package model;
// Generated May 21, 2017 1:57:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Transactions generated by hbm2java
 */
public class Transactions implements java.io.Serializable {

	private Integer idTransactions;
	private Account account;
	private Branch branch;
	private TransactionTypes transactionTypes;
	private Long enteredAmount;
	private Long accountedAmount;
	private Long feeAmount;
	private Long taxAmount;
	private String currentcyCode;
	private Long exchangeRate;
	private Integer createdBy;
	private Integer lastUpdateBy;
	private Date createdDate;
	private Date lastUpdateDate;
	private Integer approverBy;
	private Date approverDate;
	private String status;

	public Transactions() {
	}

	public Transactions(Account account, Branch branch, TransactionTypes transactionTypes) {
		this.account = account;
		this.branch = branch;
		this.transactionTypes = transactionTypes;
	}

	public Transactions(Account account, Branch branch, TransactionTypes transactionTypes, Long enteredAmount,
			Long accountedAmount, Long feeAmount, Long taxAmount, String currentcyCode, Long exchangeRate,
			Integer createdBy, Integer lastUpdateBy, Date createdDate, Date lastUpdateDate, Integer approverBy,
			Date approverDate, String status) {
		this.account = account;
		this.branch = branch;
		this.transactionTypes = transactionTypes;
		this.enteredAmount = enteredAmount;
		this.accountedAmount = accountedAmount;
		this.feeAmount = feeAmount;
		this.taxAmount = taxAmount;
		this.currentcyCode = currentcyCode;
		this.exchangeRate = exchangeRate;
		this.createdBy = createdBy;
		this.lastUpdateBy = lastUpdateBy;
		this.createdDate = createdDate;
		this.lastUpdateDate = lastUpdateDate;
		this.approverBy = approverBy;
		this.approverDate = approverDate;
		this.status = status;
	}

	public Integer getIdTransactions() {
		return this.idTransactions;
	}

	public void setIdTransactions(Integer idTransactions) {
		this.idTransactions = idTransactions;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public TransactionTypes getTransactionTypes() {
		return this.transactionTypes;
	}

	public void setTransactionTypes(TransactionTypes transactionTypes) {
		this.transactionTypes = transactionTypes;
	}

	public Long getEnteredAmount() {
		return this.enteredAmount;
	}

	public void setEnteredAmount(Long enteredAmount) {
		this.enteredAmount = enteredAmount;
	}

	public Long getAccountedAmount() {
		return this.accountedAmount;
	}

	public void setAccountedAmount(Long accountedAmount) {
		this.accountedAmount = accountedAmount;
	}

	public Long getFeeAmount() {
		return this.feeAmount;
	}

	public void setFeeAmount(Long feeAmount) {
		this.feeAmount = feeAmount;
	}

	public Long getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(Long taxAmount) {
		this.taxAmount = taxAmount;
	}

	public String getCurrentcyCode() {
		return this.currentcyCode;
	}

	public void setCurrentcyCode(String currentcyCode) {
		this.currentcyCode = currentcyCode;
	}

	public Long getExchangeRate() {
		return this.exchangeRate;
	}

	public void setExchangeRate(Long exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Integer getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(Integer lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Integer getApproverBy() {
		return this.approverBy;
	}

	public void setApproverBy(Integer approverBy) {
		this.approverBy = approverBy;
	}

	public Date getApproverDate() {
		return this.approverDate;
	}

	public void setApproverDate(Date approverDate) {
		this.approverDate = approverDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
