package model;
// Generated May 21, 2017 1:57:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TypeSavingsAccount generated by hbm2java
 */
public class TypeSavingsAccount implements java.io.Serializable {

	private Integer idTypeSavingsAccount;
	private String name;
	private String status;
	private Integer createBy;
	private Integer lastUpdateBy;
	private Date createdDate;
	private Date lastUpdateDate;
	private Set savingsAccounts = new HashSet(0);

	public TypeSavingsAccount() {
	}

	public TypeSavingsAccount(String name, String status, Integer createBy, Integer lastUpdateBy, Date createdDate,
			Date lastUpdateDate, Set savingsAccounts) {
		this.name = name;
		this.status = status;
		this.createBy = createBy;
		this.lastUpdateBy = lastUpdateBy;
		this.createdDate = createdDate;
		this.lastUpdateDate = lastUpdateDate;
		this.savingsAccounts = savingsAccounts;
	}

	public Integer getIdTypeSavingsAccount() {
		return this.idTypeSavingsAccount;
	}

	public void setIdTypeSavingsAccount(Integer idTypeSavingsAccount) {
		this.idTypeSavingsAccount = idTypeSavingsAccount;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	public Integer getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(Integer lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Set getSavingsAccounts() {
		return this.savingsAccounts;
	}

	public void setSavingsAccounts(Set savingsAccounts) {
		this.savingsAccounts = savingsAccounts;
	}

}
